# Generated by Django 2.0.4 on 2018-07-16 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products_app', '0001_initial'),
        ('Accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_name', to='Products_app.Product')),
                ('item_quantity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_quantity', to='Products_app.Product')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Accounts_app.User_class')),
            ],
        ),
    ]
