# Generated by Django 2.0.4 on 2018-07-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
    ]
