# Generated by Django 2.0.4 on 2018-07-21 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders_app', '0003_auto_20180721_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Accounts_app.User_class'),
        ),
    ]
