# Generated by Django 2.0.4 on 2018-07-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products_app', '0002_auto_20180719_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
